[package]
name = "astrid"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.9", features = ["derive"] }
cli-clipboard = "0.4.0"
uuid = { version = "1.10.0", features = ["v4"] }
